### ISSUE TITLE
Bug: Following Push Notifications and Deep Links are sometimes inconsistent

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1130] opened 2024-10-29 14:06 UTC
### Describe the bug

Following a Push notification seems to have a 50/50 chance of going to the conversation the message was received for

This is likely happening because hydration has not finished when push notification handling is done

This means we likely need to await hydration zustand state to change

### Expected behavior

Would like to make these paths 100% successful on both iOS and Android

Case 1
- App is Closed
- User Presses Chat Notification
- User Gets Navigated to Chat for message

Case 2
- App is Backgrounded
- User Presses Chat Notification
- User Gets Navigated to Chat for message

**Comment by technoplato** [comment] 2024-12-02 17:09
> This means we likely need to await hydration zustand state to change

Been wanting to look into this so 🤌

**Comment by technoplato** [comment] 2024-12-04 20:42
Repro with Loom

#### Description:

When the app is backgrounded and the user presses the chat notification, the app fails to navigate to the correct conversation consistently. This issue occurs when there are at least two conversations in the list, one being a direct message (DM) and the other a group chat between the same individuals.

#### Steps to Reproduce:

1. Have at least two conversations in the list, one DM and one group chat.
2. Refresh the app to ensure both conversations are loaded.
3. Send multiple messages in one of the conversations.
4. Background the app and wait for a chat notification.
5. Tap on the chat notification to open the app.

#### Acceptance Criteria:

- The app should navigate to the correct conversation when the chat notification is tapped.
- The notification badge on iOS should be displayed correctly.
- The issue should be reproducible consistently with the provided steps.
- Investigate the navigation pattern in the initializer to identify and resolve the navigation issue.

#### Additional Information:

- The issue seems to be related to the navigation pattern and the initial state handler in the app's initializer.
- Further investigation is needed to determine the root cause of the navigation problem.

Please refer to the attached Repro steps for more details.

**Link to Loom**

<https://loom.com/share/b41985c5ddd646b2892d240787df5ac0?src=composer>

**Comment by technoplato** [comment] 2024-12-05 16:17
@alexrisch I want to add the following to expected behavior, maybe to a different issue?

App is foregrounded
Notification received by app
App displays banner notification and unread message on conversation list item
Clicking notification takes user to appropriate conversation

**Comment by technoplato** [comment] 2024-12-05 16:20
It looks like our logic dictates not to show a notification if the user who received the message is the current user. That seems incorrect to me. 

![CleanShot 2024-12-05 at 11 19 38@2x](https://github.com/user-attachments/assets/9538d6a5-6b0d-4bcb-a78c-d4fe368f46aa)

@alexrisch Why do we not want to show an alert when the current account receives a message?

**Comment by technoplato** [comment] 2024-12-09 15:11
Fixed in above PR on iOS - getting Android environment setup now to test.

**Comment by technoplato** [comment] 2024-12-09 19:44
Android issues: https://www.loom.com/share/a34fe7214628488ea1858db23da3e4ca

**Closed** 2024-12-09 22:05 UTC
Labels: bug, 3.0.0, Deep Links
