### ISSUE TITLE
Bug: conversation.send is not a function immediately after joining a new group

### ISSUE THREAD

**Issue by technoplato** [ephemeraHQ/converse-app#1388] opened 2024-12-19 15:19 UTC
### Describe the bug

https://github.com/user-attachments/assets/ee4bfa9d-0ae2-4344-826c-4c6fa711e42e

join new group
send message

conversation.send is not a function banner at bottom presented

### Expected behavior

message sent to gropu

**Comment by thierryskoda** [comment] 2024-12-19 16:51
Can't reproduce. I think it was fixed in my recent big PR

**Closed by thierryskoda** 2024-12-19 16:51 UTC
Labels: bug
