### ISSUE TITLE
App Crash - Android

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#326] opened 2024-07-19 15:26 UTC
App crashed during testing 2 times, when I reopened, after the first time, the names shows as 0x instead of user name. Other than group chat - group chat remained with set name.

**Comment by nmalzieu** [comment] 2024-07-30 15:16
Here is a list of crashes on Android:

https://converse-app.sentry.io/issues/5619722109/events/cf604065104b417a6ca77436e2d699cf/?project=4504757120729088
https://converse-app.sentry.io/issues/4912444214/?environment=prod&project=4504757120729088&query=is:unresolved+os.name:Android&statsPeriod=24h&stream_index=1
https://converse-app.sentry.io/issues/5595661243/?environment=prod&project=4504757120729088&query=is:unresolved+os.name:Android&statsPeriod=24h&stream_index=12
https://converse-app.sentry.io/issues/5655074139/?environment=prod&project=4504757120729088&query=is:unresolved+os.name:Android&statsPeriod=24h&stream_index=16

@nplasterer @insipx @cameronvoell any of those ring a bell?
You can check the logs ("Breadcrumbs") by scrolling a bit, there sometimes are libxmtp errors

**Comment by nplasterer** [comment] 2024-08-01 02:05
Okay just going through this list and going to add color to each of the issues I see

<details><summary>UNIQUE constraint failed: group_messages.id</summary>
<p>
https://converse-app.sentry.io/issues/5619722109/events/cf604065104b417a6ca77436e2d699cf/?project=4504757120729088

[libxmtp] receive error ReceiveErrors([OpenMlsProcessMessage(ValidationError(WrongEpoch)), Storage(DieselResult(DatabaseError(UniqueViolation, "UNIQUE constraint failed: group_messages.id"))), Storage(DieselResult(DatabaseError(UniqueViolation, "UNIQUE constraint failed: group_messages.id")))])

</p>
</details> 

Maybe @insipx can speak to this one. This hopefully shouldn't be crashing the app if the group message was already written than it should just silently error and not break everything.

<details><summary>Expected URL scheme 'http' or 'https' but was 'eip155'</summary>
<p>

https://converse-app.sentry.io/issues/4912444214/?environment=prod&project=4504757120729088&query=is%3Aunresolved+os.name%3AAndroid&statsPeriod=24h&stream_index=1
java.lang.IllegalArgumentException(Expected URL scheme 'http' or 'https' but was 'eip155')

</p>
</details> 

This looks like a java error. Are you certain this is being thrown from our code? Can you give me more details on where and what is triggering this?

<details><summary>API client error: identity error: status: ResourceExhausted</summary>
<p>

https://converse-app.sentry.io/issues/5595661243/?environment=prod&project=4504757120729088&query=is%3Aunresolved+os.name%3AAndroid&statsPeriod=24h&stream_index=12

Error: Call to function 'XMTP.createFromKeyBundle' has been rejected.
→ Caused by: org.xmtp.android.library.XMTPException: Failed to create client: uniffi.xmtpv3.GenericException$Generic: Generic Error: API client error: identity error: status: ResourceExhausted

</p>
</details> 

This looks like an identity error thats maybe also related to the database. ResourcesExhausted feels like we have too many calls going to the database. So the previous calls to the database seem to be locking the database to some extent which then makes login fail. Probably a question for @insipx again.

<details><summary>OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError)))</summary>

<p>

https://converse-app.sentry.io/issues/5655074139/?environment=prod&project=4504757120729088&query=is%3Aunresolved+os.name%3AAndroid&statsPeriod=24h&stream_index=16

[libxmtp] receive error ReceiveErrors([OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(UnableToDecrypt(AeadError))), OpenMlsProcessMessage(ValidationError(WrongEpoch)), OpenMlsProcessMessage(ValidationError(WrongEpoch))])

</p>
</details> 

I was nearly certain that we fixed this issue in the latest release. Is it possible this was someone on an older build. We shouldn't be seeing this one any more going forward.

**Comment by nmalzieu** [comment] 2024-08-01 07:27
Thanks @nplasterer !

Yeah the API Client was not supposed to be there sorry.
Ok let's ignore the last one for now and see if it comes back, and let's see what @insipx has to say about the other two?

**Comment by insipx** [comment] 2024-08-01 14:45
I'll be looking into these today and see what I can find to come up with more context!

Just from the error messages

1.) The first one seems to happen because of inserting a group message that already exists in the db. Could be a race like with PublishIntents or a number of things happening there

2.) This ones interesting eip155 is an Ethereum Improvement Proposal concerning ChainIds. It lets us know which endpoint to query based on a chain identifier. So something is happening where were trying to reach an `https` url but instead using a url with `eip155` presumably to specify the chainid. There's a wrong URL somewhere but also will look into this today to figure out what's triggering it

3.) This ones definitely a [gRPC Error](https://grpc.io/docs/guides/status-codes/) and can actually be because of too many API Calls to the backend. I'll look into quota limits here, not too familiar with how gRPC handles these things but maybe we're just hitting the API too much with certain calls

**Comment by nmalzieu** [comment] 2024-08-26 14:51
I think we can close this task and open specific ones for Sentry crashes we see in the future.

**Closed by nmalzieu** 2024-08-26 14:51 UTC
Labels: bug, Android
